


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."update_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."_cnaes" (
    "codigo" bigint NOT NULL,
    "descricao" "text"
);


ALTER TABLE "public"."_cnaes" OWNER TO "postgres";


ALTER TABLE "public"."_cnaes" ALTER COLUMN "codigo" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."_cnaes_codigo_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."_estabelecimentos" (
    "id" bigint NOT NULL,
    "cnpj_basico" "text",
    "cnpj_ordem" "text",
    "cnpj_dv" "text",
    "identificador_matriz_filial" "text",
    "nome_fantasia" "text",
    "situacao_cadastral" "text",
    "data_situacao_cadastral" "text",
    "motivo_situacao_cadastral" "text",
    "nome_cidade_exterior" "text",
    "pais" "text",
    "data_inicio_atividade" "text",
    "cnae_fiscal_principal" bigint,
    "cnae_fiscal_secundaria" "text",
    "tipo_logradouro" "text",
    "logradouro" "text",
    "numero" "text",
    "complemento" "text",
    "bairro" "text",
    "cep" "text",
    "uf" "text",
    "municipio" "text",
    "ddd_1" "text",
    "telefone_1" "text",
    "ddd_2" "text",
    "telefone_2" "text",
    "ddd_fax" "text",
    "fax" "text",
    "correio_eletronico" "text",
    "situacao_especial" "text",
    "data_situacao_especial" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."_estabelecimentos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."_estabelecimentos_favoritos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "estabelecimento_id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."_estabelecimentos_favoritos" OWNER TO "postgres";


ALTER TABLE "public"."_estabelecimentos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."_estabelecimentos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."blog_categories" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."blog_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."blog_post_categories" (
    "post_id" "uuid" NOT NULL,
    "category_id" "uuid" NOT NULL
);


ALTER TABLE "public"."blog_post_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."blog_post_images" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "post_id" "uuid",
    "url" "text" NOT NULL,
    "featured" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."blog_post_images" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."blog_posts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "excerpt" "text",
    "content" "text",
    "tags" "text"[] DEFAULT '{}'::"text"[],
    "author_name" "text",
    "author_role" "text",
    "author_avatar" "text",
    "reading_time" integer DEFAULT 5,
    "featured" boolean DEFAULT false,
    "published_at" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."blog_posts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."candidato_documentos" (
    "id" bigint NOT NULL,
    "candidato_id" bigint NOT NULL,
    "titulo" "text" NOT NULL,
    "tipo" "text",
    "url" "text",
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."candidato_documentos" OWNER TO "postgres";


ALTER TABLE "public"."candidato_documentos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."candidato_documentos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."candidato_experiencias" (
    "id" bigint NOT NULL,
    "candidato_id" bigint NOT NULL,
    "cargo" "text" NOT NULL,
    "empresa" "text" NOT NULL,
    "descricao" "text",
    "data_inicio" "date" NOT NULL,
    "data_fim" "date",
    "em_andamento" boolean DEFAULT false NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."candidato_experiencias" OWNER TO "postgres";


ALTER TABLE "public"."candidato_experiencias" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."candidato_experiencias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."candidato_formacoes" (
    "id" bigint NOT NULL,
    "candidato_id" bigint NOT NULL,
    "curso" "text" NOT NULL,
    "instituicao" "text" NOT NULL,
    "grau" "text",
    "data_inicio" "date" NOT NULL,
    "data_fim" "date",
    "em_andamento" boolean DEFAULT false NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."candidato_formacoes" OWNER TO "postgres";


ALTER TABLE "public"."candidato_formacoes" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."candidato_formacoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."candidato_habilidades" (
    "id" bigint NOT NULL,
    "candidato_id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."candidato_habilidades" OWNER TO "postgres";


ALTER TABLE "public"."candidato_habilidades" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."candidato_habilidades_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."candidato_idiomas" (
    "id" bigint NOT NULL,
    "candidato_id" bigint NOT NULL,
    "idioma" "text" NOT NULL,
    "nivel" "text",
    "ordem" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "candidato_idiomas_nivel_check" CHECK (("nivel" = ANY (ARRAY['basico'::"text", 'intermediario'::"text", 'avancado'::"text", 'fluente'::"text", 'nativo'::"text"])))
);


ALTER TABLE "public"."candidato_idiomas" OWNER TO "postgres";


ALTER TABLE "public"."candidato_idiomas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."candidato_idiomas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."candidatos" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "nome_completo" "text" NOT NULL,
    "cargo_desejado" "text",
    "resumo" "text",
    "local" "text",
    "data_nascimento" "date",
    "email" "text" NOT NULL,
    "telefone" "text",
    "whatsapp" "text",
    "linkedin" "text",
    "portfolio" "text",
    "github" "text",
    "disponivel" boolean DEFAULT true NOT NULL,
    "pretensao_min" numeric(10,2),
    "pretensao_max" numeric(10,2),
    "status" "text" DEFAULT 'ativo'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "candidatos_status_check" CHECK (("status" = ANY (ARRAY['ativo'::"text", 'inativo'::"text", 'bloqueado'::"text"])))
);


ALTER TABLE "public"."candidatos" OWNER TO "postgres";


ALTER TABLE "public"."candidatos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."candidatos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."candidaturas" (
    "id" bigint NOT NULL,
    "vaga_id" bigint NOT NULL,
    "candidato_id" bigint NOT NULL,
    "status" "text" DEFAULT 'pendente'::"text" NOT NULL,
    "mensagem" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "candidaturas_status_check" CHECK (("status" = ANY (ARRAY['pendente'::"text", 'em_analise'::"text", 'entrevista'::"text", 'recusado'::"text", 'aprovado'::"text"])))
);


ALTER TABLE "public"."candidaturas" OWNER TO "postgres";


ALTER TABLE "public"."candidaturas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."candidaturas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cidades" (
    "id" integer NOT NULL,
    "estado_id" integer NOT NULL,
    "nome" "text" NOT NULL
);


ALTER TABLE "public"."cidades" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."empresa_beneficios" (
    "id" bigint NOT NULL,
    "empresa_id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."empresa_beneficios" OWNER TO "postgres";


ALTER TABLE "public"."empresa_beneficios" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."empresa_beneficios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."empresa_tecnologias" (
    "id" bigint NOT NULL,
    "empresa_id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."empresa_tecnologias" OWNER TO "postgres";


ALTER TABLE "public"."empresa_tecnologias" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."empresa_tecnologias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."empresas" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "nome_fantasia" "text" NOT NULL,
    "razao_social" "text",
    "cnpj" "text",
    "setor" "text",
    "tamanho_empresa" "text",
    "fundacao_ano" integer,
    "descricao" "text",
    "local" "text",
    "logradouro" "text",
    "numero" "text",
    "complemento" "text",
    "bairro" "text",
    "cidade" "text",
    "estado" "text",
    "cep" "text",
    "email_contato" "text",
    "telefone" "text",
    "whatsapp" "text",
    "website" "text",
    "linkedin" "text",
    "plano" "text" DEFAULT 'Gratuito'::"text" NOT NULL,
    "status" "text" DEFAULT 'ativa'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "empresas_status_check" CHECK (("status" = ANY (ARRAY['ativa'::"text", 'inativa'::"text", 'bloqueada'::"text"])))
);


ALTER TABLE "public"."empresas" OWNER TO "postgres";


ALTER TABLE "public"."empresas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."empresas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."estados" (
    "id" integer NOT NULL,
    "sigla" character(2) NOT NULL,
    "nome" "text" NOT NULL,
    "regiao" "text" NOT NULL
);


ALTER TABLE "public"."estados" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."openai_config" (
    "user_id" "uuid" NOT NULL,
    "openai_token" "text" NOT NULL,
    "model" "text" DEFAULT 'gpt-4o'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title" "text" DEFAULT 'Leitor de Vagas (IA)'::"text",
    "prompt" "text" DEFAULT 'Extraia as informações desta imagem de anúncio de vaga de emprego e retorne um objeto JSON com as seguintes chaves: "titulo" (Título da Vaga) e "descricao" (Descrição da Vaga contendo responsabilidades, requisitos, etc.). Em caso de indisponibilidade não preencha.'::"text"
);


ALTER TABLE "public"."openai_config" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "auth_id" "uuid" NOT NULL,
    "tipo" "text" NOT NULL,
    "nome" "text" NOT NULL,
    "sobrenome" "text",
    "email" "text" NOT NULL,
    "telefone" "text",
    "avatar_url" "text",
    "data_nascimento" "date",
    "area_interesse" "text",
    "razao_social" "text",
    "cnpj" "text",
    "setor" "text",
    "tamanho_empresa" "text",
    "responsavel_rh" "text",
    "status" "text" DEFAULT 'ativo'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "users_status_check" CHECK (("status" = ANY (ARRAY['ativo'::"text", 'inativo'::"text", 'bloqueado'::"text"]))),
    CONSTRAINT "users_tipo_check" CHECK (("tipo" = ANY (ARRAY['candidato'::"text", 'empregador'::"text", 'admin'::"text"])))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vaga_beneficios" (
    "id" bigint NOT NULL,
    "vaga_id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."vaga_beneficios" OWNER TO "postgres";


ALTER TABLE "public"."vaga_beneficios" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."vaga_beneficios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vaga_diferenciais" (
    "id" bigint NOT NULL,
    "vaga_id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."vaga_diferenciais" OWNER TO "postgres";


ALTER TABLE "public"."vaga_diferenciais" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."vaga_diferenciais_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vaga_requisitos" (
    "id" bigint NOT NULL,
    "vaga_id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."vaga_requisitos" OWNER TO "postgres";


ALTER TABLE "public"."vaga_requisitos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."vaga_requisitos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vaga_responsabilidades" (
    "id" bigint NOT NULL,
    "vaga_id" bigint NOT NULL,
    "texto" "text" NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."vaga_responsabilidades" OWNER TO "postgres";


ALTER TABLE "public"."vaga_responsabilidades" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."vaga_responsabilidades_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vagas" (
    "id" bigint NOT NULL,
    "titulo" "text" NOT NULL,
    "descricao" "text",
    "empresa" "text" NOT NULL,
    "local" "text",
    "modalidade" "text" NOT NULL,
    "tipo_contrato" "text",
    "nivel" "text",
    "salario_min" numeric(10,2),
    "salario_max" numeric(10,2),
    "mostrar_salario" boolean DEFAULT true NOT NULL,
    "email_contato" "text",
    "link_externo" "text",
    "status" "text" DEFAULT 'ativa'::"text" NOT NULL,
    "destaque" boolean DEFAULT false NOT NULL,
    "criado_por" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "empresa_id" bigint,
    "telefone" "text",
    "whatsapp" "text",
    "json_content" "jsonb",
    "salario_a_combinar" boolean DEFAULT false,
    CONSTRAINT "vagas_modalidade_check" CHECK (("modalidade" = ANY (ARRAY['remoto'::"text", 'hibrido'::"text", 'presencial'::"text"]))),
    CONSTRAINT "vagas_nivel_check" CHECK (("nivel" = ANY (ARRAY['estagio'::"text", 'junior'::"text", 'pleno'::"text", 'senior'::"text", 'gerente'::"text", 'diretor'::"text"]))),
    CONSTRAINT "vagas_status_check" CHECK (("status" = ANY (ARRAY['ativa'::"text", 'pausada'::"text", 'expirada'::"text", 'rascunho'::"text"]))),
    CONSTRAINT "vagas_tipo_contrato_check" CHECK (("tipo_contrato" = ANY (ARRAY['clt'::"text", 'pj'::"text", 'estagio'::"text", 'temporario'::"text", 'freelancer'::"text"])))
);


ALTER TABLE "public"."vagas" OWNER TO "postgres";


ALTER TABLE "public"."vagas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."vagas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."_cnaes"
    ADD CONSTRAINT "_cnaes_codigo_key" UNIQUE ("codigo");



ALTER TABLE ONLY "public"."_estabelecimentos_favoritos"
    ADD CONSTRAINT "_estabelecimentos_favoritos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."_estabelecimentos_favoritos"
    ADD CONSTRAINT "_estabelecimentos_favoritos_user_id_estabelecimento_id_key" UNIQUE ("user_id", "estabelecimento_id");



ALTER TABLE ONLY "public"."_estabelecimentos"
    ADD CONSTRAINT "_estabelecimentos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blog_categories"
    ADD CONSTRAINT "blog_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blog_categories"
    ADD CONSTRAINT "blog_categories_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."blog_post_categories"
    ADD CONSTRAINT "blog_post_categories_pkey" PRIMARY KEY ("post_id", "category_id");



ALTER TABLE ONLY "public"."blog_post_images"
    ADD CONSTRAINT "blog_post_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blog_posts"
    ADD CONSTRAINT "blog_posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blog_posts"
    ADD CONSTRAINT "blog_posts_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."candidato_documentos"
    ADD CONSTRAINT "candidato_documentos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidato_experiencias"
    ADD CONSTRAINT "candidato_experiencias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidato_formacoes"
    ADD CONSTRAINT "candidato_formacoes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidato_habilidades"
    ADD CONSTRAINT "candidato_habilidades_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidato_idiomas"
    ADD CONSTRAINT "candidato_idiomas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidatos"
    ADD CONSTRAINT "candidatos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidatos"
    ADD CONSTRAINT "candidatos_user_unique" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."candidaturas"
    ADD CONSTRAINT "candidaturas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidaturas"
    ADD CONSTRAINT "candidaturas_vaga_candidato_unique" UNIQUE ("vaga_id", "candidato_id");



ALTER TABLE ONLY "public"."cidades"
    ADD CONSTRAINT "cidades_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."empresa_beneficios"
    ADD CONSTRAINT "empresa_beneficios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."empresa_tecnologias"
    ADD CONSTRAINT "empresa_tecnologias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."empresas"
    ADD CONSTRAINT "empresas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."estados"
    ADD CONSTRAINT "estados_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."estados"
    ADD CONSTRAINT "estados_sigla_key" UNIQUE ("sigla");



ALTER TABLE ONLY "public"."openai_config"
    ADD CONSTRAINT "openai_config_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_auth_id_key" UNIQUE ("auth_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vaga_beneficios"
    ADD CONSTRAINT "vaga_beneficios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vaga_diferenciais"
    ADD CONSTRAINT "vaga_diferenciais_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vaga_requisitos"
    ADD CONSTRAINT "vaga_requisitos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vaga_responsabilidades"
    ADD CONSTRAINT "vaga_responsabilidades_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vagas"
    ADD CONSTRAINT "vagas_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_cand_documentos" ON "public"."candidato_documentos" USING "btree" ("candidato_id");



CREATE INDEX "idx_cand_experiencias" ON "public"."candidato_experiencias" USING "btree" ("candidato_id");



CREATE INDEX "idx_cand_formacoes" ON "public"."candidato_formacoes" USING "btree" ("candidato_id");



CREATE INDEX "idx_cand_habilidades" ON "public"."candidato_habilidades" USING "btree" ("candidato_id");



CREATE INDEX "idx_cand_idiomas" ON "public"."candidato_idiomas" USING "btree" ("candidato_id");



CREATE INDEX "idx_candidatos_local" ON "public"."candidatos" USING "btree" ("local");



CREATE INDEX "idx_candidatos_status" ON "public"."candidatos" USING "btree" ("status");



CREATE INDEX "idx_candidatos_user_id" ON "public"."candidatos" USING "btree" ("user_id");



CREATE INDEX "idx_candidaturas_candidato_id" ON "public"."candidaturas" USING "btree" ("candidato_id");



CREATE INDEX "idx_candidaturas_status" ON "public"."candidaturas" USING "btree" ("status");



CREATE INDEX "idx_candidaturas_vaga_id" ON "public"."candidaturas" USING "btree" ("vaga_id");



CREATE INDEX "idx_cidades_estado" ON "public"."cidades" USING "btree" ("estado_id");



CREATE INDEX "idx_cidades_nome" ON "public"."cidades" USING "btree" ("nome");



CREATE INDEX "idx_empresa_bens" ON "public"."empresa_beneficios" USING "btree" ("empresa_id");



CREATE INDEX "idx_empresa_tecs" ON "public"."empresa_tecnologias" USING "btree" ("empresa_id");



CREATE INDEX "idx_empresas_cnpj" ON "public"."empresas" USING "btree" ("cnpj");



CREATE INDEX "idx_empresas_local" ON "public"."empresas" USING "btree" ("local");



CREATE INDEX "idx_empresas_status" ON "public"."empresas" USING "btree" ("status");



CREATE INDEX "idx_empresas_user_id" ON "public"."empresas" USING "btree" ("user_id");



CREATE INDEX "idx_estabelecimentos_cnae_principal" ON "public"."_estabelecimentos" USING "btree" ("cnae_fiscal_principal");



CREATE INDEX "idx_estabelecimentos_cnpj_basico" ON "public"."_estabelecimentos" USING "btree" ("cnpj_basico");



CREATE INDEX "idx_estabelecimentos_municipio" ON "public"."_estabelecimentos" USING "btree" ("municipio");



CREATE INDEX "idx_estabelecimentos_nome_fantasia" ON "public"."_estabelecimentos" USING "btree" ("nome_fantasia");



CREATE INDEX "idx_estabelecimentos_uf" ON "public"."_estabelecimentos" USING "btree" ("uf");



CREATE INDEX "idx_estados_sigla" ON "public"."estados" USING "btree" ("sigla");



CREATE INDEX "idx_users_auth_id" ON "public"."users" USING "btree" ("auth_id");



CREATE INDEX "idx_users_email" ON "public"."users" USING "btree" ("email");



CREATE INDEX "idx_users_status" ON "public"."users" USING "btree" ("status");



CREATE INDEX "idx_users_tipo" ON "public"."users" USING "btree" ("tipo");



CREATE INDEX "idx_vaga_beneficios_vaga" ON "public"."vaga_beneficios" USING "btree" ("vaga_id");



CREATE INDEX "idx_vaga_diferenciais_vaga" ON "public"."vaga_diferenciais" USING "btree" ("vaga_id");



CREATE INDEX "idx_vaga_requisitos_vaga" ON "public"."vaga_requisitos" USING "btree" ("vaga_id");



CREATE INDEX "idx_vaga_responsabilidades_vaga" ON "public"."vaga_responsabilidades" USING "btree" ("vaga_id");



CREATE INDEX "idx_vagas_created_at" ON "public"."vagas" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_vagas_criado_por" ON "public"."vagas" USING "btree" ("criado_por");



CREATE INDEX "idx_vagas_empresa" ON "public"."vagas" USING "btree" ("empresa");



CREATE INDEX "idx_vagas_empresa_id" ON "public"."vagas" USING "btree" ("empresa_id");



CREATE INDEX "idx_vagas_status" ON "public"."vagas" USING "btree" ("status");



CREATE OR REPLACE TRIGGER "trigger_blog_posts_updated_at" BEFORE UPDATE ON "public"."blog_posts" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "trigger_candidatos_updated_at" BEFORE UPDATE ON "public"."candidatos" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "trigger_candidaturas_updated_at" BEFORE UPDATE ON "public"."candidaturas" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "trigger_empresas_updated_at" BEFORE UPDATE ON "public"."empresas" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "trigger_users_updated_at" BEFORE UPDATE ON "public"."users" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



CREATE OR REPLACE TRIGGER "trigger_vagas_updated_at" BEFORE UPDATE ON "public"."vagas" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();



ALTER TABLE ONLY "public"."_estabelecimentos_favoritos"
    ADD CONSTRAINT "_estabelecimentos_favoritos_estabelecimento_id_fkey" FOREIGN KEY ("estabelecimento_id") REFERENCES "public"."_estabelecimentos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."_estabelecimentos_favoritos"
    ADD CONSTRAINT "_estabelecimentos_favoritos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."blog_post_categories"
    ADD CONSTRAINT "blog_post_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."blog_categories"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."blog_post_categories"
    ADD CONSTRAINT "blog_post_categories_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."blog_posts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."blog_post_images"
    ADD CONSTRAINT "blog_post_images_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."blog_posts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidato_documentos"
    ADD CONSTRAINT "candidato_documentos_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "public"."candidatos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidato_experiencias"
    ADD CONSTRAINT "candidato_experiencias_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "public"."candidatos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidato_formacoes"
    ADD CONSTRAINT "candidato_formacoes_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "public"."candidatos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidato_habilidades"
    ADD CONSTRAINT "candidato_habilidades_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "public"."candidatos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidato_idiomas"
    ADD CONSTRAINT "candidato_idiomas_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "public"."candidatos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidatos"
    ADD CONSTRAINT "candidatos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidaturas"
    ADD CONSTRAINT "candidaturas_candidato_id_fkey" FOREIGN KEY ("candidato_id") REFERENCES "public"."candidatos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."candidaturas"
    ADD CONSTRAINT "candidaturas_vaga_id_fkey" FOREIGN KEY ("vaga_id") REFERENCES "public"."vagas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."cidades"
    ADD CONSTRAINT "cidades_estado_id_fkey" FOREIGN KEY ("estado_id") REFERENCES "public"."estados"("id");



ALTER TABLE ONLY "public"."empresa_beneficios"
    ADD CONSTRAINT "empresa_beneficios_empresa_id_fkey" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."empresa_tecnologias"
    ADD CONSTRAINT "empresa_tecnologias_empresa_id_fkey" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."empresas"
    ADD CONSTRAINT "empresas_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."openai_config"
    ADD CONSTRAINT "openai_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_auth_id_fkey" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vaga_beneficios"
    ADD CONSTRAINT "vaga_beneficios_vaga_id_fkey" FOREIGN KEY ("vaga_id") REFERENCES "public"."vagas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vaga_diferenciais"
    ADD CONSTRAINT "vaga_diferenciais_vaga_id_fkey" FOREIGN KEY ("vaga_id") REFERENCES "public"."vagas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vaga_requisitos"
    ADD CONSTRAINT "vaga_requisitos_vaga_id_fkey" FOREIGN KEY ("vaga_id") REFERENCES "public"."vagas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vaga_responsabilidades"
    ADD CONSTRAINT "vaga_responsabilidades_vaga_id_fkey" FOREIGN KEY ("vaga_id") REFERENCES "public"."vagas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vagas"
    ADD CONSTRAINT "vagas_criado_por_fkey" FOREIGN KEY ("criado_por") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."vagas"
    ADD CONSTRAINT "vagas_empresa_id_fkey" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE SET NULL;



CREATE POLICY "Admin pode inserir e atualizar" ON "public"."openai_config" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Admins can manage blog_categories" ON "public"."blog_categories" USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."auth_id" = "auth"."uid"()) AND ("users"."tipo" = 'admin'::"text")))));



CREATE POLICY "Admins can manage blog_post_categories" ON "public"."blog_post_categories" USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."auth_id" = "auth"."uid"()) AND ("users"."tipo" = 'admin'::"text")))));



CREATE POLICY "Admins can manage blog_post_images" ON "public"."blog_post_images" USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."auth_id" = "auth"."uid"()) AND ("users"."tipo" = 'admin'::"text")))));



CREATE POLICY "Admins can manage blog_posts" ON "public"."blog_posts" USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."auth_id" = "auth"."uid"()) AND ("users"."tipo" = 'admin'::"text")))));



CREATE POLICY "Apenas admin pode ler a configuração da OpenAI" ON "public"."openai_config" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Public can read blog_categories" ON "public"."blog_categories" FOR SELECT USING (true);



CREATE POLICY "Public can read blog_post_categories" ON "public"."blog_post_categories" FOR SELECT USING (true);



CREATE POLICY "Public can read blog_post_images" ON "public"."blog_post_images" FOR SELECT USING (true);



CREATE POLICY "Public can read blog_posts" ON "public"."blog_posts" FOR SELECT USING (true);



CREATE POLICY "Usuários deletam seus próprios favoritos estabelecimentos" ON "public"."_estabelecimentos_favoritos" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Usuários inserem seus próprios favoritos estabelecimentos" ON "public"."_estabelecimentos_favoritos" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Usuários veem seus próprios favoritos estabelecimentos" ON "public"."_estabelecimentos_favoritos" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."_cnaes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."_estabelecimentos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."_estabelecimentos_favoritos" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "admin_delete_all" ON "public"."users" FOR DELETE USING ((( SELECT "users_1"."tipo"
   FROM "public"."users" "users_1"
  WHERE ("users_1"."auth_id" = "auth"."uid"())) = 'admin'::"text"));



CREATE POLICY "admin_select_all" ON "public"."users" FOR SELECT USING ((( SELECT "users_1"."tipo"
   FROM "public"."users" "users_1"
  WHERE ("users_1"."auth_id" = "auth"."uid"())) = 'admin'::"text"));



CREATE POLICY "admin_update_all" ON "public"."users" FOR UPDATE USING ((( SELECT "users_1"."tipo"
   FROM "public"."users" "users_1"
  WHERE ("users_1"."auth_id" = "auth"."uid"())) = 'admin'::"text"));



CREATE POLICY "aux_delete" ON "public"."vaga_beneficios" FOR DELETE USING (true);



CREATE POLICY "aux_delete" ON "public"."vaga_diferenciais" FOR DELETE USING (true);



CREATE POLICY "aux_delete" ON "public"."vaga_requisitos" FOR DELETE USING (true);



CREATE POLICY "aux_delete" ON "public"."vaga_responsabilidades" FOR DELETE USING (true);



CREATE POLICY "aux_insert" ON "public"."vaga_beneficios" FOR INSERT WITH CHECK (true);



CREATE POLICY "aux_insert" ON "public"."vaga_diferenciais" FOR INSERT WITH CHECK (true);



CREATE POLICY "aux_insert" ON "public"."vaga_requisitos" FOR INSERT WITH CHECK (true);



CREATE POLICY "aux_insert" ON "public"."vaga_responsabilidades" FOR INSERT WITH CHECK (true);



CREATE POLICY "aux_select_public" ON "public"."vaga_beneficios" FOR SELECT USING (true);



CREATE POLICY "aux_select_public" ON "public"."vaga_diferenciais" FOR SELECT USING (true);



CREATE POLICY "aux_select_public" ON "public"."vaga_requisitos" FOR SELECT USING (true);



CREATE POLICY "aux_select_public" ON "public"."vaga_responsabilidades" FOR SELECT USING (true);



ALTER TABLE "public"."blog_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blog_post_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blog_post_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blog_posts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "cand_aux_delete" ON "public"."candidato_documentos" FOR DELETE USING (true);



CREATE POLICY "cand_aux_delete" ON "public"."candidato_experiencias" FOR DELETE USING (true);



CREATE POLICY "cand_aux_delete" ON "public"."candidato_formacoes" FOR DELETE USING (true);



CREATE POLICY "cand_aux_delete" ON "public"."candidato_habilidades" FOR DELETE USING (true);



CREATE POLICY "cand_aux_delete" ON "public"."candidato_idiomas" FOR DELETE USING (true);



CREATE POLICY "cand_aux_insert" ON "public"."candidato_documentos" FOR INSERT WITH CHECK (true);



CREATE POLICY "cand_aux_insert" ON "public"."candidato_experiencias" FOR INSERT WITH CHECK (true);



CREATE POLICY "cand_aux_insert" ON "public"."candidato_formacoes" FOR INSERT WITH CHECK (true);



CREATE POLICY "cand_aux_insert" ON "public"."candidato_habilidades" FOR INSERT WITH CHECK (true);



CREATE POLICY "cand_aux_insert" ON "public"."candidato_idiomas" FOR INSERT WITH CHECK (true);



CREATE POLICY "cand_aux_select" ON "public"."candidato_documentos" FOR SELECT USING (true);



CREATE POLICY "cand_aux_select" ON "public"."candidato_experiencias" FOR SELECT USING (true);



CREATE POLICY "cand_aux_select" ON "public"."candidato_formacoes" FOR SELECT USING (true);



CREATE POLICY "cand_aux_select" ON "public"."candidato_habilidades" FOR SELECT USING (true);



CREATE POLICY "cand_aux_select" ON "public"."candidato_idiomas" FOR SELECT USING (true);



ALTER TABLE "public"."candidato_documentos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."candidato_experiencias" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."candidato_formacoes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."candidato_habilidades" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."candidato_idiomas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."candidatos" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "candidatos_insert" ON "public"."candidatos" FOR INSERT WITH CHECK (true);



CREATE POLICY "candidatos_select_all" ON "public"."candidatos" FOR SELECT USING (true);



CREATE POLICY "candidatos_select_own" ON "public"."candidatos" FOR SELECT USING (("user_id" = ( SELECT "users"."id"
   FROM "public"."users"
  WHERE ("users"."auth_id" = "auth"."uid"()))));



CREATE POLICY "candidatos_update_own" ON "public"."candidatos" FOR UPDATE USING (("user_id" = ( SELECT "users"."id"
   FROM "public"."users"
  WHERE ("users"."auth_id" = "auth"."uid"()))));



ALTER TABLE "public"."candidaturas" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "candidaturas_admin_all" ON "public"."candidaturas" USING (true);



CREATE POLICY "candidaturas_insert_own" ON "public"."candidaturas" FOR INSERT WITH CHECK (true);



CREATE POLICY "candidaturas_select_employer" ON "public"."candidaturas" FOR SELECT USING (("vaga_id" IN ( SELECT "v"."id"
   FROM ("public"."vagas" "v"
     JOIN "public"."users" "u" ON (("v"."criado_por" = "u"."id")))
  WHERE ("u"."auth_id" = "auth"."uid"()))));



CREATE POLICY "candidaturas_select_own" ON "public"."candidaturas" FOR SELECT USING (("candidato_id" IN ( SELECT "c"."id"
   FROM ("public"."candidatos" "c"
     JOIN "public"."users" "u" ON (("c"."user_id" = "u"."id")))
  WHERE ("u"."auth_id" = "auth"."uid"()))));



CREATE POLICY "candidaturas_update_employer" ON "public"."candidaturas" FOR UPDATE USING (("vaga_id" IN ( SELECT "v"."id"
   FROM ("public"."vagas" "v"
     JOIN "public"."users" "u" ON (("v"."criado_por" = "u"."id")))
  WHERE ("u"."auth_id" = "auth"."uid"()))));



ALTER TABLE "public"."cidades" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "cidades_select_public" ON "public"."cidades" FOR SELECT USING (true);



ALTER TABLE "public"."empresa_beneficios" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "empresa_beneficios_select" ON "public"."empresa_beneficios" FOR SELECT USING (true);



ALTER TABLE "public"."empresa_tecnologias" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "empresa_tecnologias_select" ON "public"."empresa_tecnologias" FOR SELECT USING (true);



ALTER TABLE "public"."empresas" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "empresas_insert" ON "public"."empresas" FOR INSERT WITH CHECK (true);



CREATE POLICY "empresas_select_all" ON "public"."empresas" FOR SELECT USING (true);



CREATE POLICY "empresas_update_own" ON "public"."empresas" FOR UPDATE USING (("user_id" = ( SELECT "users"."id"
   FROM "public"."users"
  WHERE ("users"."auth_id" = "auth"."uid"()))));



CREATE POLICY "estabelecimentos_delete" ON "public"."_estabelecimentos" FOR DELETE USING (true);



CREATE POLICY "estabelecimentos_insert" ON "public"."_estabelecimentos" FOR INSERT WITH CHECK (true);



CREATE POLICY "estabelecimentos_select_public" ON "public"."_estabelecimentos" FOR SELECT USING (true);



ALTER TABLE "public"."estados" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "estados_select_public" ON "public"."estados" FOR SELECT USING (true);



ALTER TABLE "public"."openai_config" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "users_insert_own" ON "public"."users" FOR INSERT WITH CHECK (("auth"."uid"() = "auth_id"));



CREATE POLICY "users_select_own" ON "public"."users" FOR SELECT USING (("auth"."uid"() = "auth_id"));



CREATE POLICY "users_update_own" ON "public"."users" FOR UPDATE USING (("auth"."uid"() = "auth_id"));



ALTER TABLE "public"."vaga_beneficios" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vaga_diferenciais" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vaga_requisitos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vaga_responsabilidades" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vagas" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "vagas_insert" ON "public"."vagas" FOR INSERT WITH CHECK (true);



CREATE POLICY "vagas_select_own" ON "public"."vagas" FOR SELECT USING (("criado_por" = ( SELECT "users"."id"
   FROM "public"."users"
  WHERE ("users"."auth_id" = "auth"."uid"()))));



CREATE POLICY "vagas_select_public" ON "public"."vagas" FOR SELECT USING (("status" = 'ativa'::"text"));



CREATE POLICY "vagas_update_own" ON "public"."vagas" FOR UPDATE USING (("criado_por" = ( SELECT "users"."id"
   FROM "public"."users"
  WHERE ("users"."auth_id" = "auth"."uid"()))));



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at"() TO "service_role";



GRANT ALL ON TABLE "public"."_cnaes" TO "anon";
GRANT ALL ON TABLE "public"."_cnaes" TO "authenticated";
GRANT ALL ON TABLE "public"."_cnaes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."_cnaes_codigo_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."_cnaes_codigo_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."_cnaes_codigo_seq" TO "service_role";



GRANT ALL ON TABLE "public"."_estabelecimentos" TO "anon";
GRANT ALL ON TABLE "public"."_estabelecimentos" TO "authenticated";
GRANT ALL ON TABLE "public"."_estabelecimentos" TO "service_role";



GRANT ALL ON TABLE "public"."_estabelecimentos_favoritos" TO "anon";
GRANT ALL ON TABLE "public"."_estabelecimentos_favoritos" TO "authenticated";
GRANT ALL ON TABLE "public"."_estabelecimentos_favoritos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."_estabelecimentos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."_estabelecimentos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."_estabelecimentos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."blog_categories" TO "anon";
GRANT ALL ON TABLE "public"."blog_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."blog_categories" TO "service_role";



GRANT ALL ON TABLE "public"."blog_post_categories" TO "anon";
GRANT ALL ON TABLE "public"."blog_post_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."blog_post_categories" TO "service_role";



GRANT ALL ON TABLE "public"."blog_post_images" TO "anon";
GRANT ALL ON TABLE "public"."blog_post_images" TO "authenticated";
GRANT ALL ON TABLE "public"."blog_post_images" TO "service_role";



GRANT ALL ON TABLE "public"."blog_posts" TO "anon";
GRANT ALL ON TABLE "public"."blog_posts" TO "authenticated";
GRANT ALL ON TABLE "public"."blog_posts" TO "service_role";



GRANT ALL ON TABLE "public"."candidato_documentos" TO "anon";
GRANT ALL ON TABLE "public"."candidato_documentos" TO "authenticated";
GRANT ALL ON TABLE "public"."candidato_documentos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."candidato_documentos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."candidato_documentos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."candidato_documentos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."candidato_experiencias" TO "anon";
GRANT ALL ON TABLE "public"."candidato_experiencias" TO "authenticated";
GRANT ALL ON TABLE "public"."candidato_experiencias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."candidato_experiencias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."candidato_experiencias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."candidato_experiencias_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."candidato_formacoes" TO "anon";
GRANT ALL ON TABLE "public"."candidato_formacoes" TO "authenticated";
GRANT ALL ON TABLE "public"."candidato_formacoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."candidato_formacoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."candidato_formacoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."candidato_formacoes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."candidato_habilidades" TO "anon";
GRANT ALL ON TABLE "public"."candidato_habilidades" TO "authenticated";
GRANT ALL ON TABLE "public"."candidato_habilidades" TO "service_role";



GRANT ALL ON SEQUENCE "public"."candidato_habilidades_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."candidato_habilidades_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."candidato_habilidades_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."candidato_idiomas" TO "anon";
GRANT ALL ON TABLE "public"."candidato_idiomas" TO "authenticated";
GRANT ALL ON TABLE "public"."candidato_idiomas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."candidato_idiomas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."candidato_idiomas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."candidato_idiomas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."candidatos" TO "anon";
GRANT ALL ON TABLE "public"."candidatos" TO "authenticated";
GRANT ALL ON TABLE "public"."candidatos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."candidatos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."candidatos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."candidatos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."candidaturas" TO "anon";
GRANT ALL ON TABLE "public"."candidaturas" TO "authenticated";
GRANT ALL ON TABLE "public"."candidaturas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."candidaturas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."candidaturas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."candidaturas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cidades" TO "anon";
GRANT ALL ON TABLE "public"."cidades" TO "authenticated";
GRANT ALL ON TABLE "public"."cidades" TO "service_role";



GRANT ALL ON TABLE "public"."empresa_beneficios" TO "anon";
GRANT ALL ON TABLE "public"."empresa_beneficios" TO "authenticated";
GRANT ALL ON TABLE "public"."empresa_beneficios" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresa_beneficios_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresa_beneficios_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresa_beneficios_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empresa_tecnologias" TO "anon";
GRANT ALL ON TABLE "public"."empresa_tecnologias" TO "authenticated";
GRANT ALL ON TABLE "public"."empresa_tecnologias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresa_tecnologias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresa_tecnologias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresa_tecnologias_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empresas" TO "anon";
GRANT ALL ON TABLE "public"."empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."empresas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."estados" TO "anon";
GRANT ALL ON TABLE "public"."estados" TO "authenticated";
GRANT ALL ON TABLE "public"."estados" TO "service_role";



GRANT ALL ON TABLE "public"."openai_config" TO "anon";
GRANT ALL ON TABLE "public"."openai_config" TO "authenticated";
GRANT ALL ON TABLE "public"."openai_config" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vaga_beneficios" TO "anon";
GRANT ALL ON TABLE "public"."vaga_beneficios" TO "authenticated";
GRANT ALL ON TABLE "public"."vaga_beneficios" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vaga_beneficios_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vaga_beneficios_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vaga_beneficios_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vaga_diferenciais" TO "anon";
GRANT ALL ON TABLE "public"."vaga_diferenciais" TO "authenticated";
GRANT ALL ON TABLE "public"."vaga_diferenciais" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vaga_diferenciais_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vaga_diferenciais_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vaga_diferenciais_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vaga_requisitos" TO "anon";
GRANT ALL ON TABLE "public"."vaga_requisitos" TO "authenticated";
GRANT ALL ON TABLE "public"."vaga_requisitos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vaga_requisitos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vaga_requisitos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vaga_requisitos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vaga_responsabilidades" TO "anon";
GRANT ALL ON TABLE "public"."vaga_responsabilidades" TO "authenticated";
GRANT ALL ON TABLE "public"."vaga_responsabilidades" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vaga_responsabilidades_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vaga_responsabilidades_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vaga_responsabilidades_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vagas" TO "anon";
GRANT ALL ON TABLE "public"."vagas" TO "authenticated";
GRANT ALL ON TABLE "public"."vagas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."vagas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vagas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vagas_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







