-- Tabela para armazenar caminhos de imagens na biblioteca
CREATE TABLE IF NOT EXISTS public.media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_path TEXT NOT NULL,
    url_publica TEXT NOT NULL,
    nome_original TEXT,
    mime_type TEXT,
    size_bytes BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (opcional, dependendo do uso, mas como é admin, createAdminClient bypassa)
ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;

-- Bucket no storage (Nota: Isso geralmente é feito via Dashboard do Supabase ou SQL direto)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('media', 'media', true) ON CONFLICT DO NOTHING;
