-- =============================================
-- Migration: Rename vagas_categorias to vaga_categorias
-- =============================================

-- 1. Rename the table
ALTER TABLE public.vagas_categorias RENAME TO vaga_categorias;

-- 2. Rename the constraints/indexes if auto-generated by Supabase/Postgres
ALTER INDEX IF EXISTS vagas_categorias_pkey RENAME TO vaga_categorias_pkey;
ALTER INDEX IF EXISTS vagas_categorias_slug_key RENAME TO vaga_categorias_slug_key;

-- 3. Rename the policies
ALTER POLICY "vagas_categorias_select_public" ON public.vaga_categorias RENAME TO "vaga_categorias_select_public";
ALTER POLICY "vagas_categorias_insert_admin" ON public.vaga_categorias RENAME TO "vaga_categorias_insert_admin";
ALTER POLICY "vagas_categorias_update_admin" ON public.vaga_categorias RENAME TO "vaga_categorias_update_admin";
ALTER POLICY "vagas_categorias_delete_admin" ON public.vaga_categorias RENAME TO "vaga_categorias_delete_admin";
